on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Executable
        run: swift build -c release --arch arm64 --arch x86_64
      - name: Copy Server Executable
        run: cp .build/apple/Products/Release/stable-diffusion-rpc stable-diffusion-rpc
      - name: Archive Server Executable
        uses: actions/upload-artifact@v2
        with:
          name: stable-diffusion-rpc
          path: stable-diffusion-rpc
      - name: Copy Control Executable
        run: cp .build/apple/Products/Release/stable-diffusion-ctl stable-diffusion-ctl
      - name: Archive Control Executable
        uses: actions/upload-artifact@v2
        with:
          name: stable-diffusion-rpc
          path: stable-diffusion-rpc
  format:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Swift Format
        run: swiftformat --lint Package.swift Sources
  lint:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Swift Lint
        run: swiftlint Package.swift Sources
