name: macOS
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Executable
        run: swift build -c release --arch arm64 --arch x86_64
      - name: Copy Executable
        run: cp .build/apple/Products/Release/StableDiffusionServer StableDiffusionServer
      - name: Archive Executable
        uses: actions/upload-artifact@v2
        with:
          name: StableDiffusionServer
          path: StableDiffusionServer
  format:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Swift Format
        run: swiftformat --lint Package.swift Sources
  lint:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Swift Lint
        run: swiftlint Package.swift Sources
